---
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "simple-hook.fullname" . }}'
  labels:
    {{- include "simple-hook.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: {{ .Values.hook.type }}
    helm.sh/hook-weight: '0'
    helm.sh/hook-delete-policy: {{ .Values.hook.deletePolicy }}
data:
  init.sh: |-
  {{- .Values.script | nindent 4 }}
