---
apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ include "simple-hook.fullname" . }}'
  labels:
    {{- include "simple-hook.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: {{ .Values.hook.type }}
    helm.sh/hook-weight: '10'
    helm.sh/hook-delete-policy: {{ .Values.hook.deletePolicy }}
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  {{- with .Values.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  template:
    metadata:
      name: '{{ include "simple-hook.fullname" . }}'
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "simple-hook.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: '{{ include "simple-hook.fullname" . }}'
      serviceAccountName: '{{ include "simple-hook.fullname" . }}'
      restartPolicy: {{ .Values.restartPolicy }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      dnsPolicy: '{{ .Values.dnsPolicy }}'
      securityContext:
      {{- with .Values.podSecurityContext -}}
        {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: simple-hook
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- else }}
          command:
            - /scripts/init.sh
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- with .Values.extraEnv -}}
            {{ toYaml . | nindent 12 }}
            {{- end }}
          resources:
          {{- with .Values.resources -}}
            {{ toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
          {{- with .Values.containerSecurityContext -}}
            {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if not .Values.command }}
            - mountPath: /scripts
              name: config-volume
            {{- end }}
            {{- if .Values.kubeVolume }}
            - mountPath: /.kube
              name: kube
            {{- end }}
          {{- with .Values.extraVolumeMounts -}}
          {{ toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if not .Values.command }}
        - configMap:
            defaultMode: 0755
            name: '{{ include "simple-hook.fullname" . }}'
          name: config-volume
        {{- end }}
        {{- if .Values.kubeVolume }}
        - emptyDir: {}
          name: kube
        {{- end }}
      {{- with .Values.extraVolumes -}}
      {{ toYaml . | nindent 8 }}
      {{- end }}
