{{ if .Values.rbac.create -}}
{{- if .Values.rbac.rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: '{{ eq .Values.rbac.scope "cluster" | ternary "ClusterRole" "Role" }}'
metadata:
  name: '{{ include "simple-hook.fullname" . }}'
  labels:
    {{- include "simple-hook.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: {{ .Values.hook.type }}
    helm.sh/hook-weight: '0'
    helm.sh/hook-delete-policy: {{ .Values.hook.deletePolicy }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{ if eq .Values.rbac.scope "cluster" -}}
kind: ClusterRoleBinding
{{ else -}}
kind: RoleBinding
{{ end -}}
metadata:
  name: '{{ include "simple-hook.fullname" . }}'
  labels:
    {{- include "simple-hook.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: {{ .Values.hook.type }}
    helm.sh/hook-weight: '0'
    helm.sh/hook-delete-policy: {{ .Values.hook.deletePolicy }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.rbac.rules }}
  kind: '{{ eq .Values.rbac.scope "cluster" | ternary "ClusterRole" "Role" }}'
  name: '{{ include "simple-hook.fullname" . }}'
  {{- else }}
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRole }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: '{{ include "simple-hook.fullname" . }}'
    namespace: "{{ .Release.Namespace }}"
{{ end -}}
