{{- if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "restart-controller.fullname" . }}
  labels:
    {{- include "restart-controller.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "restart-controller.selectorLabels" . | nindent 6 }}
  egress:
    - toEntities:
        - kube-apiserver
{{- end }}
