apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "restart-controller.fullname" . }}
  labels:
    {{- include "restart-controller.labels" . | nindent 4 }}
data:
  script.sh: |-
    {{- .Files.Get "files/script.sh" | nindent 4 }}
