apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drover.apiFilter.fullname" . }}
  labels:
    {{- include "drover.componentLabels" (dict "root" . "component" "api-filter") | nindent 4 }}
automountServiceAccountToken: false
