apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "drover.fullname" . }}-password
  labels:
    {{- include "drover.labels" . | nindent 4 }}
spec:
  length: {{ .Values.serviceUser.password.length }}
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "drover.credentialsName" . }}
  labels:
    {{- include "drover.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.serviceUser.password.refreshInterval | quote }}
  refreshPolicy: Periodic
  target:
    name: {{ include "drover.credentialsName" . }}
    creationPolicy: Owner
    template:
      data:
        username: drover
        password: "{{ `{{ .password }}` }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ include "drover.fullname" . }}-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "drover.projectSync.credentialsName" . }}
  labels:
    {{- include "drover.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.serviceUser.password.refreshInterval | quote }}
  refreshPolicy: Periodic
  target:
    name: {{ include "drover.projectSync.credentialsName" . }}
    creationPolicy: Owner
    template:
      data:
        username: drover-project-sync
        password: "{{ `{{ .password }}` }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ include "drover.fullname" . }}-password
