apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drover.projectSync.fullname" . }}
  labels:
    {{- include "drover.componentLabels" (dict "root" . "component" "project-sync") | nindent 4 }}
automountServiceAccountToken: false
