apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drover.rotateToken.fullname" . }}
  labels:
    {{- include "drover.componentLabels" (dict "root" . "component" "rotate-token") | nindent 4 }}
