apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drover.projectSync.user" . }}
  namespace: cattle-local-user-passwords
  labels:
    {{- include "drover.labels" . | nindent 4 }}
  annotations:
    cattle.io/password-hash: pbkdf2sha3512
type: Opaque
