{{- $component := dict "root" . "component" "rotate-token" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "drover.rotateToken.fullname" . }}-password
  namespace: cattle-local-user-passwords
  labels:
    {{- include "drover.componentLabels" $component | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - u-drover
      - {{ include "drover.projectSync.user" . }}
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "drover.rotateToken.fullname" . }}-password
  namespace: cattle-local-user-passwords
  labels:
    {{- include "drover.componentLabels" $component | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "drover.rotateToken.fullname" . }}-password
subjects:
  - kind: ServiceAccount
    name: {{ include "drover.rotateToken.fullname" . }}
    namespace: {{ .Release.Namespace }}
