{{- $component := dict "root" . "component" "rancher-rbac" }}
{{- $name := include "drover.serviceUser.rancherRbac.fullname" . }}
{{- $fullname := include "drover.fullname" . }}
{{- $projectSync := include "drover.projectSync.fullname" . }}
{{- $annotations := dict "hook" "pre-delete,post-install,post-upgrade" "weight" 0 }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "drover.componentLabels" $component | nindent 4 }}
  annotations:
    {{- include "drover.serviceUser.hookAnnotations" $annotations | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}
  labels:
    {{- include "drover.componentLabels" $component | nindent 4 }}
  annotations:
    {{- include "drover.serviceUser.hookAnnotations" $annotations | nindent 4 }}
rules:
  {{- include "drover.apiFilter.rules" . | nindent 2 }}
  {{- include "drover.projectSync.rules" . | nindent 2 }}
  - apiGroups:
      - management.cattle.io
    resources:
      - roletemplates
      - globalroles
      - globalrolebindings
    verbs:
      - get
      - create
      - patch
      - delete
  - apiGroups:
      - management.cattle.io
    resources:
      - globalroles
    resourceNames:
      - {{ $fullname }}
      - {{ $projectSync }}
      - user-base
    verbs:
      - bind
      - escalate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}
  labels:
    {{- include "drover.componentLabels" $component | nindent 4 }}
  annotations:
    {{- include "drover.serviceUser.hookAnnotations" $annotations | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  namespace: local
  labels:
    {{- include "drover.componentLabels" $component | nindent 4 }}
  annotations:
    {{- include "drover.serviceUser.hookAnnotations" $annotations | nindent 4 }}
rules:
  - apiGroups:
      - management.cattle.io
    resources:
      - clusterroletemplatebindings
    verbs:
      - get
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  namespace: local
  labels:
    {{- include "drover.componentLabels" $component | nindent 4 }}
  annotations:
    {{- include "drover.serviceUser.hookAnnotations" $annotations | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: {{ .Release.Namespace }}
