{{- if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "opentelemetry-syslog-collector.fullname" . }}
  labels:
    {{- include "opentelemetry-syslog-collector.labels" . | nindent 4 }}
specs:
  - endpointSelector:
      matchLabels:
        {{- include "opentelemetry-syslog-collector.otelOperatorLabels" . | nindent 8 }}
    ingress:
      - fromEntities:
          - world
          - cluster
        toPorts:
          - ports:
              {{- $seen := dict }}
              {{- range $name, $svc := .Values.services }}
              {{- if $svc.enabled }}
              {{- range $svc.ports }}
              {{- $tp := (.targetPort | default .port) }}
              {{- $key := printf "%s-%d" .protocol $tp }}
              {{- if not (hasKey $seen $key) }}
              {{- $_ := set $seen $key true }}
              - port: {{ $tp | quote }}
                protocol: {{ .protocol }}
              {{- end }}
              {{- end }}
              {{- end }}
              {{- end }}
              - port: {{ .Values.exporter.port | quote }}
                protocol: TCP
              - port: "8888"
                protocol: TCP
              - port: "13133"
                protocol: TCP
    egress:
      - toEndpoints:
          - matchLabels:
              k8s:io.kubernetes.pod.namespace: kube-system
              k8s-app: kube-dns
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
      - toEntities:
          - cluster
          - world
  {{- if .Values.loadgen.enabled }}
  - endpointSelector:
      matchLabels:
        {{- include "opentelemetry-syslog-collector.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: loadgen
    egress:
      - toEndpoints:
          - matchLabels:
              k8s:io.kubernetes.pod.namespace: kube-system
              k8s-app: kube-dns
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
      - toEndpoints:
          - matchLabels:
              {{- include "opentelemetry-syslog-collector.otelOperatorLabels" . | nindent 14 }}
        toPorts:
          - ports:
              {{- $seen := dict }}
              {{- range $name, $svc := .Values.services }}
              {{- if $svc.enabled }}
              {{- range $svc.ports }}
              {{- $tp := (.targetPort | default .port) }}
              {{- $key := printf "%s-%d" .protocol $tp }}
              {{- if not (hasKey $seen $key) }}
              {{- $_ := set $seen $key true }}
              - port: {{ $tp | quote }}
                protocol: {{ .protocol }}
              {{- end }}
              {{- end }}
              {{- end }}
              {{- end }}
  {{- end }}
{{- end }}
