apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentelemetry-syslog-collector.fullname" . }}-syslogng
  labels:
    {{- include "opentelemetry-syslog-collector.labels" . | nindent 4 }}
data:
  syslog-ng.conf: |
    {{- tpl .Values.syslogng.config . | nindent 4 }}
