---
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "simple-cronjob.fullname" . }}'
  labels:
    {{- include "simple-cronjob.labels" . | nindent 4 }}
  annotations: {}
data:
  init.sh: |-
  {{- .Values.script | nindent 4 }}
