apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-local-dns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-local-dns.labels" . | nindent 4 }}
    addonmanager.kubernetes.io/mode: Reconcile
data:
  Corefile: |
    {{- .Values.corefile | trim | nindent 4 }}
