apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.upstreamService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-local-dns.releaseLabels" . | nindent 4 }}
    {{- toYaml .Values.upstreamService.selector | nindent 4 }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: KubeDNSUpstream
spec:
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    {{- toYaml .Values.upstreamService.selector | nindent 4 }}
