---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "drover-policies.fullname" . }}-kyverno-read
  labels:
    {{- include "drover-policies.labels" . | nindent 4 }}
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
    rbac.kyverno.io/aggregate-to-background-controller: "true"
    rbac.kyverno.io/aggregate-to-reports-controller: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - grpcroutes
      - httproutes
      - listenersets
      - tlsroutes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
      - servicemonitors
    verbs:
      - get
      - list
      - watch
{{- if (index .Values.policies "prometheus-monitors").enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "drover-policies.fullname" . }}-kyverno-background-controller
  labels:
    {{- include "drover-policies.labels" . | nindent 4 }}
    rbac.kyverno.io/aggregate-to-background-controller: "true"
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
      - servicemonitors
    verbs:
      - update
      - patch
{{- end }}
