---
apiVersion: v2
name: drover
description: Tenancy extensions for Rancher
type: application
version: 0.21.2
appVersion: "0.16.2"
kubeVersion: '>=1.27.0-0'
home: https://github.com/evil8io/drover

sources:
  - https://github.com/evil8io/drover
